name: YouTube Shorts History Bot (Auto 3x Sehari WITA)

on:
  schedule:
    - cron: '0 23,4,10 * * *'
  workflow_dispatch:

permissions:
  contents: write    # <--- WAJIB DITAMBAHKAN AGAR BOT BISA MENGUBAH REPOSITORY

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install -y imagemagick
        sudo sed -i 's/rights="none" pattern="@\*"/rights="read|write" pattern="@\*"/g' /etc/ImageMagick-6/policy.xml
        pip install -r requirements.txt

    - name: Run Bot Script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
      run: |
        python main.py

    # ---> BLOK BARU: MENYIMPAN HISTORY KE GITHUB <---
    - name: Commit and Push History
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add history.txt
        # Cek apakah ada perubahan, jika ada lakukan commit, jika tidak abaikan
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update history [skip ci]" && git push)
